version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: uptime_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: uptime_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
