version: "3.9"

services: 
  postgres:
    image: postgres:latest
    container_name: uptime_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

